# Application port
server:
  port: 7777
  servlet:
    context-path: /spring-session
    session:
      timeout: 5m

# JPA configuration
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: MX_AUDIT
    password: MX_AUDIT
    url: jdbc:oracle:thin:@localhost:1521:xe
    initialization-mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    open-in-view: true
    properties:
      release_mode: after_transaction
      agressive_release: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

